name: Update dependency graph

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-graph:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Chryse
      uses: chryse-hdl/setup-chryse@v2
      with:
        source-ref: main
        athena-source-ref: main

    - uses: scalacenter/sbt-dependency-submission@v2
